# Generated by Django 3.1.7 on 2021-05-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(max_length=200)),
                ('FileS3', models.CharField(max_length=200)),
                ('Job_id', models.CharField(max_length=200)),
                ('status_to_s3', models.BooleanField(default=False)),
                ('status_of_job', models.BooleanField(default=False)),
                ('Logtime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Logtime'],
            },
        ),
    ]
